
import { Grade, Strand, OA } from './types';

export const CURRICULUM_OAS: OA[] = [
  // --- 1° BÁSICO ---
  { id: 'g1-oa1', code: 'OA 1', grade: Grade.G1, strand: Strand.Numbers, description: 'Contar números del 0 al 100 de 1 en 1, de 2 en 2, de 5 en 5 y de 10 en 10.' },
  { id: 'g1-oa2', code: 'OA 2', grade: Grade.G1, strand: Strand.Numbers, description: 'Identificar el orden y la posición de objetos (1° al 10°).' },
  { id: 'g1-oa3', code: 'OA 3', grade: Grade.G1, strand: Strand.Numbers, description: 'Leer números del 0 al 20 y representarlos.' },
  { id: 'g1-oa4', code: 'OA 4', grade: Grade.G1, strand: Strand.Numbers, description: 'Comparar y ordenar números del 0 al 20.' },
  { id: 'g1-oa5', code: 'OA 5', grade: Grade.G1, strand: Strand.Numbers, description: 'Estimar cantidades hasta 20.' },
  { id: 'g1-oa6', code: 'OA 6', grade: Grade.G1, strand: Strand.Numbers, description: 'Componer y descomponer números del 0 al 20.' },
  { id: 'g1-oa7', code: 'OA 7', grade: Grade.G1, strand: Strand.Numbers, description: 'Describir y aplicar estrategias de cálculo mental para adiciones y sustracciones hasta 20.' },
  { id: 'g1-oa8', code: 'OA 8', grade: Grade.G1, strand: Strand.Numbers, description: 'Determinar unidades y decenas en números de 0 a 20.' },
  { id: 'g1-oa9', code: 'OA 9', grade: Grade.G1, strand: Strand.Numbers, description: 'Demostrar que comprenden la adición y la sustracción de números del 0 al 20.' },
  { id: 'g1-oa10', code: 'OA 10', grade: Grade.G1, strand: Strand.Numbers, description: 'Demostrar que la adición y la sustracción son operaciones inversas.' },
  { id: 'g1-oa11', code: 'OA 11', grade: Grade.G1, strand: Strand.Algebra, description: 'Reconocer, describir, crear y continuar patrones repetitivos.' },
  { id: 'g1-oa12', code: 'OA 12', grade: Grade.G1, strand: Strand.Algebra, description: 'Describir y registrar la igualdad y la desigualdad usando los signos (=, >, <).' },
  { id: 'g1-oa13', code: 'OA 13', grade: Grade.G1, strand: Strand.Geometry, description: 'Describir, comparar y construir figuras 2D.' },
  { id: 'g1-oa14', code: 'OA 14', grade: Grade.G1, strand: Strand.Geometry, description: 'Identificar figuras 3D en el entorno y relacionarlas con figuras 2D.' },
  { id: 'g1-oa15', code: 'OA 15', grade: Grade.G1, strand: Strand.Geometry, description: 'Describir la posición de objetos y personas.' },
  { id: 'g1-oa16', code: 'OA 16', grade: Grade.G1, strand: Strand.Measurement, description: 'Usar unidades no estandarizadas de tiempo para secuenciar eventos.' },
  { id: 'g1-oa17', code: 'OA 17', grade: Grade.G1, strand: Strand.Measurement, description: 'Usar un calendario para identificar días, semanas, meses y fechas.' },
  { id: 'g1-oa18', code: 'OA 18', grade: Grade.G1, strand: Strand.Measurement, description: 'Identificar y comparar la longitud de objetos.' },
  { id: 'g1-oa19', code: 'OA 19', grade: Grade.G1, strand: Strand.Data, description: 'Recolectar y registrar datos para responder preguntas estadísticas.' },
  { id: 'g1-oa20', code: 'OA 20', grade: Grade.G1, strand: Strand.Data, description: 'Construir, leer e interpretar pictogramas.' },

  // --- 2° BÁSICO ---
  { id: 'g2-oa1', code: 'OA 1', grade: Grade.G2, strand: Strand.Numbers, description: 'Contar números naturales hasta 1.000.' },
  { id: 'g2-oa2', code: 'OA 2', grade: Grade.G2, strand: Strand.Numbers, description: 'Leer números hasta 1.000 y representarlos.' },
  { id: 'g2-oa3', code: 'OA 3', grade: Grade.G2, strand: Strand.Numbers, description: 'Comparar y ordenar números naturales hasta 1.000.' },
  { id: 'g2-oa4', code: 'OA 4', grade: Grade.G2, strand: Strand.Numbers, description: 'Estimar cantidades hasta 100.' },
  { id: 'g2-oa5', code: 'OA 5', grade: Grade.G2, strand: Strand.Numbers, description: 'Componer y descomponer números hasta 1.000.' },
  { id: 'g2-oa6', code: 'OA 6', grade: Grade.G2, strand: Strand.Numbers, description: 'Estrategias de cálculo mental para adición y sustracción hasta 100.' },
  { id: 'g2-oa7', code: 'OA 7', grade: Grade.G2, strand: Strand.Numbers, description: 'Identificar unidades y decenas hasta 100.' },
  { id: 'g2-oa8', code: 'OA 8', grade: Grade.G2, strand: Strand.Numbers, description: 'Demostrar que comprenden la adición y sustracción en el ámbito 0-100.' },
  { id: 'g2-oa9', code: 'OA 9', grade: Grade.G2, strand: Strand.Numbers, description: 'Demostrar que comprenden la adición y la sustracción en el ámbito del 0 al 1.000.' },
  { id: 'g2-oa10', code: 'OA 10', grade: Grade.G2, strand: Strand.Numbers, description: 'Resolver problemas rutinarios y no rutinarios en el ámbito 0-100.' },
  { id: 'g2-oa11', code: 'OA 11', grade: Grade.G2, strand: Strand.Numbers, description: 'Demostrar que comprenden la multiplicación.' },
  { id: 'g2-oa12', code: 'OA 12', grade: Grade.G2, strand: Strand.Numbers, description: 'Crear y resolver problemas de multiplicación.' },
  { id: 'g2-oa13', code: 'OA 13', grade: Grade.G2, strand: Strand.Algebra, description: 'Demostrar, comprender y describir patrones numéricos.' },
  { id: 'g2-oa14', code: 'OA 14', grade: Grade.G2, strand: Strand.Algebra, description: 'Representar y describir la posición de objetos.' },
  { id: 'g2-oa15', code: 'OA 15', grade: Grade.G2, strand: Strand.Geometry, description: 'Describir, comparar y construir figuras 2D.' },
  { id: 'g2-oa16', code: 'OA 16', grade: Grade.G2, strand: Strand.Geometry, description: 'Describir, comparar y construir figuras 3D.' },
  { id: 'g2-oa17', code: 'OA 17', grade: Grade.G2, strand: Strand.Measurement, description: 'Identificar días, semanas, meses y fechas en el calendario.' },
  { id: 'g2-oa18', code: 'OA 18', grade: Grade.G2, strand: Strand.Measurement, description: 'Leer horas exactas y medias horas en relojes análogos.' },
  { id: 'g2-oa19', code: 'OA 19', grade: Grade.G2, strand: Strand.Measurement, description: 'Determinar la longitud de objetos usando unidades estandarizadas (cm, m).' },
  { id: 'g2-oa20', code: 'OA 20', grade: Grade.G2, strand: Strand.Data, description: 'Recolectar y registrar datos para responder preguntas estadísticas.' },
  { id: 'g2-oa21', code: 'OA 21', grade: Grade.G2, strand: Strand.Data, description: 'Realizar encuestas y organizar datos en tablas.' },
  { id: 'g2-oa22', code: 'OA 22', grade: Grade.G2, strand: Strand.Data, description: 'Leer e interpretar pictogramas y gráficos de barra simple.' },

  // --- 3° BÁSICO ---
  { id: 'g3-oa1', code: 'OA 1', grade: Grade.G3, strand: Strand.Numbers, description: 'Contar números naturales hasta 1.000.' },
  { id: 'g3-oa2', code: 'OA 2', grade: Grade.G3, strand: Strand.Numbers, description: 'Leer y representar números hasta 1.000.' },
  { id: 'g3-oa3', code: 'OA 3', grade: Grade.G3, strand: Strand.Numbers, description: 'Comparar y ordenar números hasta 1.000.' },
  { id: 'g3-oa4', code: 'OA 4', grade: Grade.G3, strand: Strand.Numbers, description: 'Estimar cantidades hasta 1.000.' },
  { id: 'g3-oa5', code: 'OA 5', grade: Grade.G3, strand: Strand.Numbers, description: 'Identificar valor posicional: unidades, decenas y centenas.' },
  { id: 'g3-oa6', code: 'OA 6', grade: Grade.G3, strand: Strand.Numbers, description: 'Estrategias de cálculo mental para adiciones y sustracciones hasta 100.' },
  { id: 'g3-oa7', code: 'OA 7', grade: Grade.G3, strand: Strand.Numbers, description: 'Demostrar que comprenden la adición y la sustracción hasta 1.000.' },
  { id: 'g3-oa8', code: 'OA 8', grade: Grade.G3, strand: Strand.Numbers, description: 'Tablas de multiplicar de 2, 5 y 10.' },
  { id: 'g3-oa9', code: 'OA 9', grade: Grade.G3, strand: Strand.Numbers, description: 'Demostrar que comprenden la división.' },
  { id: 'g3-oa10', code: 'OA 10', grade: Grade.G3, strand: Strand.Numbers, description: 'Resolver problemas rutinarios y no rutinarios que involucren las cuatro operaciones.' },
  { id: 'g3-oa11', code: 'OA 11', grade: Grade.G3, strand: Strand.Numbers, description: 'Demostrar que comprenden las fracciones con denominadores 2, 4, 8, 3, 6.' },
  { id: 'g3-oa12', code: 'OA 12', grade: Grade.G3, strand: Strand.Algebra, description: 'Generar, describir y registrar patrones numéricos.' },
  { id: 'g3-oa13', code: 'OA 13', grade: Grade.G3, strand: Strand.Algebra, description: 'Resolver ecuaciones de un paso.' },
  { id: 'g3-oa14', code: 'OA 14', grade: Grade.G3, strand: Strand.Geometry, description: 'Describir la localización de un objeto en una cuadrícula.' },
  { id: 'g3-oa15', code: 'OA 15', grade: Grade.G3, strand: Strand.Geometry, description: 'Localización en mapas o cuadrículas usando coordenadas.' },
  { id: 'g3-oa16', code: 'OA 16', grade: Grade.G3, strand: Strand.Geometry, description: 'Describir cubos y paralelepípedos.' },
  { id: 'g3-oa17', code: 'OA 17', grade: Grade.G3, strand: Strand.Geometry, description: 'Reconocer ángulos en el entorno.' },
  { id: 'g3-oa18', code: 'OA 18', grade: Grade.G3, strand: Strand.Measurement, description: 'Leer horas en relojes análogos y digitales.' },
  { id: 'g3-oa19', code: 'OA 19', grade: Grade.G3, strand: Strand.Measurement, description: 'Determinar el perímetro de figuras regulares e irregulares.' },
  { id: 'g3-oa20', code: 'OA 20', grade: Grade.G3, strand: Strand.Measurement, description: 'Leer y registrar tiempo usando unidades de medida (minutos, horas).' },
  { id: 'g3-oa21', code: 'OA 21', grade: Grade.G3, strand: Strand.Measurement, description: 'Unidades de tiempo: días, semanas, meses.' },
  { id: 'g3-oa22', code: 'OA 22', grade: Grade.G3, strand: Strand.Measurement, description: 'Longitud: cm y m.' },
  { id: 'g3-oa23', code: 'OA 23', grade: Grade.G3, strand: Strand.Data, description: 'Realizar encuestas y clasificar datos.' },
  { id: 'g3-oa24', code: 'OA 24', grade: Grade.G3, strand: Strand.Data, description: 'Organizar datos en tablas de conteo.' },
  { id: 'g3-oa25', code: 'OA 25', grade: Grade.G3, strand: Strand.Data, description: 'Interpretar pictogramas y gráficos de barra con escala.' },

  // --- 4° BÁSICO ---
  { id: 'g4-oa1', code: 'OA 1', grade: Grade.G4, strand: Strand.Numbers, description: 'Representar y describir números hasta 10.000.' },
  { id: 'g4-oa2', code: 'OA 2', grade: Grade.G4, strand: Strand.Numbers, description: 'Comparar y ordenar números hasta 10.000.' },
  { id: 'g4-oa3', code: 'OA 3', grade: Grade.G4, strand: Strand.Numbers, description: 'Adición y sustracción de números hasta 1.000.' },
  { id: 'g4-oa4', code: 'OA 4', grade: Grade.G4, strand: Strand.Numbers, description: 'Fundamentar algoritmos de la adición y sustracción.' },
  { id: 'g4-oa5', code: 'OA 5', grade: Grade.G4, strand: Strand.Numbers, description: 'Multiplicación de 3 dígitos por 1 dígito.' },
  { id: 'g4-oa6', code: 'OA 6', grade: Grade.G4, strand: Strand.Numbers, description: 'División con dividendos de 2 dígitos y divisores de 1.' },
  { id: 'g4-oa7', code: 'OA 7', grade: Grade.G4, strand: Strand.Numbers, description: 'Resolver problemas rutinarios y no rutinarios.' },
  { id: 'g4-oa8', code: 'OA 8', grade: Grade.G4, strand: Strand.Numbers, description: 'Fracciones: denominadores 2, 3, 4, 5, 6, 8, 10, 12.' },
  { id: 'g4-oa9', code: 'OA 9', grade: Grade.G4, strand: Strand.Numbers, description: 'Fracciones equivalentes.' },
  { id: 'g4-oa10', code: 'OA 10', grade: Grade.G4, strand: Strand.Numbers, description: 'Comparar fracciones con igual denominador.' },
  { id: 'g4-oa11', code: 'OA 11', grade: Grade.G4, strand: Strand.Numbers, description: 'Suma y resta de fracciones con igual denominador.' },
  { id: 'g4-oa12', code: 'OA 12', grade: Grade.G4, strand: Strand.Numbers, description: 'Números decimales: décimos y centésimos.' },
  { id: 'g4-oa13', code: 'OA 13', grade: Grade.G4, strand: Strand.Algebra, description: 'Patrones numéricos en tablas.' },
  { id: 'g4-oa14', code: 'OA 14', grade: Grade.G4, strand: Strand.Algebra, description: 'Resolver ecuaciones e inecuaciones de un paso.' },
  { id: 'g4-oa15', code: 'OA 15', grade: Grade.G4, strand: Strand.Geometry, description: 'Localización absoluta en cuadrículas.' },
  { id: 'g4-oa16', code: 'OA 16', grade: Grade.G4, strand: Strand.Geometry, description: 'Localización absoluta usando coordenadas.' },
  { id: 'g4-oa17', code: 'OA 17', grade: Grade.G4, strand: Strand.Geometry, description: 'Línea de simetría en figuras 2D.' },
  { id: 'g4-oa18', code: 'OA 18', grade: Grade.G4, strand: Strand.Geometry, description: 'Traslaciones, rotaciones y reflexiones.' },
  { id: 'g4-oa19', code: 'OA 19', grade: Grade.G4, strand: Strand.Geometry, description: 'Ángulos menores a 180°.' },
  { id: 'g4-oa20', code: 'OA 20', grade: Grade.G4, strand: Strand.Measurement, description: 'Leer horas en relojes digitales y análogos.' },
  { id: 'g4-oa21', code: 'OA 21', grade: Grade.G4, strand: Strand.Measurement, description: 'Perímetro de figuras geométricas.' },
  { id: 'g4-oa22', code: 'OA 22', grade: Grade.G4, strand: Strand.Measurement, description: 'Medir longitudes: m, cm, mm.' },
  { id: 'g4-oa23', code: 'OA 23', grade: Grade.G4, strand: Strand.Measurement, description: 'Área de rectángulos y cuadrados.' },
  { id: 'g4-oa24', code: 'OA 24', grade: Grade.G4, strand: Strand.Measurement, description: 'Volumen de cuerpos simples.' },
  { id: 'g4-oa25', code: 'OA 25', grade: Grade.G4, strand: Strand.Data, description: 'Realizar encuestas y organizar datos.' },
  { id: 'g4-oa26', code: 'OA 26', grade: Grade.G4, strand: Strand.Data, description: 'Tablas de doble entrada.' },
  { id: 'g4-oa27', code: 'OA 27', grade: Grade.G4, strand: Strand.Data, description: 'Leer e interpretar pictogramas y gráficos de barra.' },

  // --- 5° BÁSICO ---
  { id: 'g5-oa1', code: 'OA 1', grade: Grade.G5, strand: Strand.Numbers, description: 'Números hasta 1.000 millones: lectura y representación.' },
  { id: 'g5-oa2', code: 'OA 2', grade: Grade.G5, strand: Strand.Numbers, description: 'Estrategias de cálculo mental: multiplicación y división.' },
  { id: 'g5-oa3', code: 'OA 3', grade: Grade.G5, strand: Strand.Numbers, description: 'Algoritmo de la multiplicación de hasta 2 dígitos.' },
  { id: 'g5-oa4', code: 'OA 4', grade: Grade.G5, strand: Strand.Numbers, description: 'División con dividendos de 3 dígitos y divisores de 1.' },
  { id: 'g5-oa5', code: 'OA 5', grade: Grade.G5, strand: Strand.Numbers, description: 'Resolver problemas con las cuatro operaciones.' },
  { id: 'g5-oa6', code: 'OA 6', grade: Grade.G5, strand: Strand.Numbers, description: 'Resolver operaciones combinadas.' },
  { id: 'g5-oa7', code: 'OA 7', grade: Grade.G5, strand: Strand.Numbers, description: 'Fracciones propias e impropias.' },
  { id: 'g5-oa8', code: 'OA 8', grade: Grade.G5, strand: Strand.Numbers, description: 'Fracciones equivalentes y amplificación/simplificación.' },
  { id: 'g5-oa9', code: 'OA 9', grade: Grade.G5, strand: Strand.Numbers, description: 'Adición y sustracción de fracciones con distinto denominador.' },
  { id: 'g5-oa10', code: 'OA 10', grade: Grade.G5, strand: Strand.Numbers, description: 'Números decimales hasta la milésima.' },
  { id: 'g5-oa11', code: 'OA 11', grade: Grade.G5, strand: Strand.Numbers, description: 'Comparar y ordenar decimales hasta la milésima.' },
  { id: 'g5-oa12', code: 'OA 12', grade: Grade.G5, strand: Strand.Numbers, description: 'Adición y sustracción de números decimales.' },
  { id: 'g5-oa13', code: 'OA 13', grade: Grade.G5, strand: Strand.Algebra, description: 'Ecuaciones e inecuaciones de un paso.' },
  { id: 'g5-oa14', code: 'OA 14', grade: Grade.G5, strand: Strand.Algebra, description: 'Sucesiones numéricas y reglas de formación.' },
  { id: 'g5-oa15', code: 'OA 15', grade: Grade.G5, strand: Strand.Algebra, description: 'Lenguaje algebraico básico.' },
  { id: 'g5-oa16', code: 'OA 16', grade: Grade.G5, strand: Strand.Geometry, description: 'Identificar aristas y caras paralelas/perpendiculares en figuras 3D.' },
  { id: 'g5-oa17', code: 'OA 17', grade: Grade.G5, strand: Strand.Geometry, description: 'Figuras 3D: caras, aristas y vértices.' },
  { id: 'g5-oa18', code: 'OA 18', grade: Grade.G5, strand: Strand.Geometry, description: 'Congruencia de figuras planas.' },
  { id: 'g5-oa19', code: 'OA 19', grade: Grade.G5, strand: Strand.Geometry, description: 'Plano cartesiano y coordenadas.' },
  { id: 'g5-oa20', code: 'OA 20', grade: Grade.G5, strand: Strand.Measurement, description: 'Medición de ángulos con transportador.' },
  { id: 'g5-oa21', code: 'OA 21', grade: Grade.G5, strand: Strand.Measurement, description: 'Modelos de prismas y pirámides.' },
  { id: 'g5-oa22', code: 'OA 22', grade: Grade.G5, strand: Strand.Measurement, description: 'Área de triángulos, paralelogramos y trapecios.' },
  { id: 'g5-oa23', code: 'OA 23', grade: Grade.G5, strand: Strand.Data, description: 'Calcular el promedio de un conjunto de datos.' },
  { id: 'g5-oa24', code: 'OA 24', grade: Grade.G5, strand: Strand.Data, description: 'Realizar encuestas y clasificar respuestas.' },
  { id: 'g5-oa25', code: 'OA 25', grade: Grade.G5, strand: Strand.Data, description: 'Diagrama de tallo y hojas.' },
  { id: 'g5-oa26', code: 'OA 26', grade: Grade.G5, strand: Strand.Data, description: 'Gráficos de barra doble y circulares.' },

  // --- 6° BÁSICO ---
  { id: 'g6-oa1', code: 'OA 1', grade: Grade.G6, strand: Strand.Numbers, description: 'Factores y múltiplos: números primos y compuestos.' },
  { id: 'g6-oa2', code: 'OA 2', grade: Grade.G6, strand: Strand.Numbers, description: 'Mínimo Común Múltiplo.' },
  { id: 'g6-oa3', code: 'OA 3', grade: Grade.G6, strand: Strand.Numbers, description: 'Concepto de razón.' },
  { id: 'g6-oa4', code: 'OA 4', grade: Grade.G6, strand: Strand.Numbers, description: 'Concepto de porcentaje.' },
  { id: 'g6-oa5', code: 'OA 5', grade: Grade.G6, strand: Strand.Numbers, description: 'Representar razones y porcentajes.' },
  { id: 'g6-oa6', code: 'OA 6', grade: Grade.G6, strand: Strand.Numbers, description: 'Resolver problemas de razones y porcentajes.' },
  { id: 'g6-oa7', code: 'OA 7', grade: Grade.G6, strand: Strand.Numbers, description: 'Multiplicación y división de fracciones.' },
  { id: 'g6-oa8', code: 'OA 8', grade: Grade.G6, strand: Strand.Numbers, description: 'Operaciones combinadas con fracciones y decimales.' },
  { id: 'g6-oa9', code: 'OA 9', grade: Grade.G6, strand: Strand.Numbers, description: 'Multiplicación y división de decimales.' },
  { id: 'g6-oa10', code: 'OA 10', grade: Grade.G6, strand: Strand.Algebra, description: 'Representar y generalizar relaciones.' },
  { id: 'g6-oa11', code: 'OA 11', grade: Grade.G6, strand: Strand.Algebra, description: 'Ecuaciones de primer grado con una incógnita.' },
  { id: 'g6-oa12', code: 'OA 12', grade: Grade.G6, strand: Strand.Algebra, description: 'Inecuaciones de primer grado.' },
  { id: 'g6-oa13', code: 'OA 13', grade: Grade.G6, strand: Strand.Geometry, description: 'Área de superficie de cubos y paralelepípedos.' },
  { id: 'g6-oa14', code: 'OA 14', grade: Grade.G6, strand: Strand.Geometry, description: 'Volumen de cubos y paralelepípedos.' },
  { id: 'g6-oa15', code: 'OA 15', grade: Grade.G6, strand: Strand.Geometry, description: 'Teselaciones regulares.' },
  { id: 'g6-oa16', code: 'OA 16', grade: Grade.G6, strand: Strand.Geometry, description: 'Simetría rotacional y traslacional.' },
  { id: 'g6-oa17', code: 'OA 17', grade: Grade.G6, strand: Strand.Geometry, description: 'Ángulos en un triángulo y cuadrilátero.' },
  { id: 'g6-oa18', code: 'OA 18', grade: Grade.G6, strand: Strand.Geometry, description: 'Ángulos en rectas que se cortan.' },
  { id: 'g6-oa19', code: 'OA 19', grade: Grade.G6, strand: Strand.Measurement, description: 'Longitud y área del círculo (aproximación).' },
  { id: 'g6-oa20', code: 'OA 20', grade: Grade.G6, strand: Strand.Measurement, description: 'Convertir unidades de volumen.' },
  { id: 'g6-oa21', code: 'OA 21', grade: Grade.G6, strand: Strand.Data, description: 'Comparar conjuntos de datos.' },
  { id: 'g6-oa22', code: 'OA 22', grade: Grade.G6, strand: Strand.Data, description: 'Gráficos de barra doble y circulares.' },
  { id: 'g6-oa23', code: 'OA 23', grade: Grade.G6, strand: Strand.Data, description: 'Diagramas de puntos y de tallo y hojas.' },
  { id: 'g6-oa24', code: 'OA 24', grade: Grade.G6, strand: Strand.Data, description: 'Concepto de probabilidad experimental.' },

  // --- 7° BÁSICO ---
  { id: 'g7-oa1', code: 'OA 1', grade: Grade.G7, strand: Strand.Numbers, description: 'Adición y sustracción de números enteros.' },
  { id: 'g7-oa2', code: 'OA 2', grade: Grade.G7, strand: Strand.Numbers, description: 'Multiplicación y división de fracciones y decimales positivos.' },
  { id: 'g7-oa3', code: 'OA 3', grade: Grade.G7, strand: Strand.Numbers, description: 'Resolver problemas con fracciones y decimales.' },
  { id: 'g7-oa4', code: 'OA 4', grade: Grade.G7, strand: Strand.Numbers, description: 'Concepto de porcentaje y diversas aplicaciones.' },
  { id: 'g7-oa5', code: 'OA 5', grade: Grade.G7, strand: Strand.AlgebraFunctions, description: 'Lenguaje algebraico para generalizar relaciones.' },
  { id: 'g7-oa6', code: 'OA 6', grade: Grade.G7, strand: Strand.AlgebraFunctions, description: 'Ecuaciones e inecuaciones lineales.' },
  { id: 'g7-oa7', code: 'OA 7', grade: Grade.G7, strand: Strand.AlgebraFunctions, description: 'Proporcionalidad directa.' },
  { id: 'g7-oa8', code: 'OA 8', grade: Grade.G7, strand: Strand.AlgebraFunctions, description: 'Variable en expresiones algebraicas.' },
  { id: 'g7-oa9', code: 'OA 9', grade: Grade.G7, strand: Strand.Geometry, description: 'Puntos, rectas y planos en el espacio.' },
  { id: 'g7-oa10', code: 'OA 10', grade: Grade.G7, strand: Strand.Geometry, description: 'Vistas de figuras 3D.' },
  { id: 'g7-oa11', code: 'OA 11', grade: Grade.G7, strand: Strand.Geometry, description: 'El círculo: diámetro, perímetro y Pi.' },
  { id: 'g7-oa12', code: 'OA 12', grade: Grade.G7, strand: Strand.Geometry, description: 'Fórmulas de área y perímetro del círculo.' },
  { id: 'g7-oa13', code: 'OA 13', grade: Grade.G7, strand: Strand.Geometry, description: 'Superficie y volumen de prismas rectos.' },
  { id: 'g7-oa14', code: 'OA 14', grade: Grade.G7, strand: Strand.ProbStats, description: 'Población, muestra y variables.' },
  { id: 'g7-oa15', code: 'OA 15', grade: Grade.G7, strand: Strand.ProbStats, description: 'Tablas de frecuencias y gráficos circulares.' },
  { id: 'g7-oa16', code: 'OA 16', grade: Grade.G7, strand: Strand.ProbStats, description: 'Gráficos de barra doble y circulares.' },
  { id: 'g7-oa17', code: 'OA 17', grade: Grade.G7, strand: Strand.ProbStats, description: 'Medidas de tendencia central (media, mediana, moda).' },
  { id: 'g7-oa18', code: 'OA 18', grade: Grade.G7, strand: Strand.ProbStats, description: 'Probabilidad experimental y teórica básica.' },

  // --- 8° BÁSICO ---
  { id: 'g8-oa1', code: 'OA 1', grade: Grade.G8, strand: Strand.Numbers, description: 'Multiplicación y división de números enteros.' },
  { id: 'g8-oa2', code: 'OA 2', grade: Grade.G8, strand: Strand.Numbers, description: 'Operaciones con números racionales.' },
  { id: 'g8-oa3', code: 'OA 3', grade: Grade.G8, strand: Strand.Numbers, description: 'Potencias de base racional y exponente entero.' },
  { id: 'g8-oa4', code: 'OA 4', grade: Grade.G8, strand: Strand.Numbers, description: 'Raíces cuadradas de números naturales.' },
  { id: 'g8-oa5', code: 'OA 5', grade: Grade.G8, strand: Strand.AlgebraFunctions, description: 'Variaciones porcentuales.' },
  { id: 'g8-oa6', code: 'OA 6', grade: Grade.G8, strand: Strand.AlgebraFunctions, description: 'Operaciones con expresiones algebraicas y ecuaciones.' },
  { id: 'g8-oa7', code: 'OA 7', grade: Grade.G8, strand: Strand.AlgebraFunctions, description: 'Noción de función (tablas y gráficos).' },
  { id: 'g8-oa8', code: 'OA 8', grade: Grade.G8, strand: Strand.AlgebraFunctions, description: 'Funciones lineales y afines.' },
  { id: 'g8-oa9', code: 'OA 9', grade: Grade.G8, strand: Strand.Geometry, description: 'Semejanza de figuras planas.' },
  { id: 'g8-oa10', code: 'OA 10', grade: Grade.G8, strand: Strand.Geometry, description: 'Transformaciones isométricas.' },
  { id: 'g8-oa11', code: 'OA 11', grade: Grade.G8, strand: Strand.Geometry, description: 'Superficie y volumen de cilindros y prismas.' },
  { id: 'g8-oa12', code: 'OA 12', grade: Grade.G8, strand: Strand.Geometry, description: 'Teorema de Pitágoras.' },
  { id: 'g8-oa13', code: 'OA 13', grade: Grade.G8, strand: Strand.ProbStats, description: 'Medidas de tendencia central y de posición.' },
  { id: 'g8-oa14', code: 'OA 14', grade: Grade.G8, strand: Strand.ProbStats, description: 'Diagramas de cajón y dispersión.' },
  { id: 'g8-oa15', code: 'OA 15', grade: Grade.G8, strand: Strand.ProbStats, description: 'Probabilidad mediante experimentación.' },
  { id: 'g8-oa16', code: 'OA 16', grade: Grade.G8, strand: Strand.ProbStats, description: 'Probabilidad teórica mediante la regla de Laplace.' },
  { id: 'g8-oa17', code: 'OA 17', grade: Grade.G8, strand: Strand.ProbStats, description: 'Probabilidad de eventos compuestos (diagramas de árbol y tablas).' }
];

export const ASSESSMENT_DESCRIPTIONS: Record<string, string> = {
  'Prueba Sumativa': 'Evaluación formal de cierre de proceso con calificación al libro.',
  'Evaluación de Unidad': 'Instrumento integrador que abarca múltiples objetivos de una unidad temática.',
  'Ensayo SIMCE': 'Formato estandarizado con selección múltiple enfocado en habilidades cognitivas.',
  'Aprendizaje Basado en Problemas (ABP-Prob)': 'Resolución de una situación problemática compleja abierta.',
  'Aprendizaje Basado en Proyectos (ABP-Proy)': 'Experiencia articulada en torno a un producto público y fases de investigación.',
  'Evaluación de Habilidades': 'Foco exclusivo en Modelar, Argumentar, Representar y Resolver Problemas.',
  'Ticket de Salida (Formativa)': 'Actividad breve de cierre focalizada en un indicador específico de logro.',
  'Evaluación Diagnóstica': 'Exploración de conocimientos previos y prerrequisitos del nivel anterior.',
  'Rúbrica de Desempeño': 'Matriz detallada para evaluar procesos y razonamiento matemático.',
  'Escala de Apreciación / Lista de Cotejo': 'Observación de conductas, actitudes y habilidades procedimentales.',
};
